source "http://rubygems.org"

gem "sinatra"
gem "carrierwave"
#gem "puma"
gem "haml"
gem "sequel"
gem "carrierwave-sequel", :require => "carrierwave/sequel"
gem "sqlite3"
# gem "pry-byebug"
gem "time_ago_in_words"
gem "mini_magick"
#gem 'pg'
#gem "better_eroor"
#gem "spring"
#gem "database_cleaner"
#gem "database_cleaner"
#gem "database_cleaner"